PersonalConsulting section --> Page "Personal consulting"
SoftRyzen-internship/psychologist pull request #10
Opened 2023-06-09 15:26 UTC by MagisterUnivers

2023-06-13 14:45 UTC, nadiakhoptiuk requested changes

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/pages/consultations.js
>  };
додати типізацію для пропсів

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.jsx
> +};
додати типізацію для пропса data

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.jsx
> +      <section className={s.sectionBG}>
додати перевірки 
{data && ... 

data?.heading 
 та ін

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.jsx
> +              alt="1"
додати опис українською для зображення

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +@media screen and (min-width: 768px) {
залишити по одному медіа правилі для кожного екрану, всі властивості - всередину

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +/* .subtitle::before {
зайві коментарі прибрати

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +/* .subtitle p::before {
коментарі прибрати

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  padding-left: 24px;
падінг перемістити вгору)

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  font-style: normal;
тут зазвичай normal, немає потреби писати, якщо він наслідується від батьківського елемента

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    padding-left: 36px;
падінг перемістити вгору)

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    padding-left: 30px;
падінг перемістити вгору)

2023-06-13 14:45 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.jsx
> +            <ul className={s.mainList}>
можливо, краще li i ul замінити на div, нам їх розділити треба суто візуально

2023-06-13 19:11 UTC, MagisterUnivers commented on src/pages/consultations.js
>  };
+

2023-06-13 19:13 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.jsx
> +              alt="1"
+

2023-06-13 19:18 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +@media screen and (min-width: 768px) {
+

2023-06-13 19:22 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  padding-left: 24px;
+

2023-06-13 19:24 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  font-style: normal;
+

2023-06-13 19:24 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    padding-left: 36px;
+

2023-06-13 19:25 UTC, MagisterUnivers commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    padding-left: 30px;
+

2023-06-16 09:44 UTC, nadiakhoptiuk requested changes

2023-06-16 09:44 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +
для мобільного краще обмежити ширину заголовка згідно з макетом - 222px

2023-06-16 09:44 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +/* .subtitle::before {
не прибрав

2023-06-16 09:44 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +/* .subtitle p::before {
теж не прибрав

2023-06-16 09:44 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  margin-bottom: 16px;
додати
.mainListItem:last-child {
  margin-bottom: 0;
}

2023-06-16 09:44 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +  margin-top: 24px;
margin-top з цього селектора перенести на .listWrapper
і на десктопі змінити на 36

2023-06-19 09:33 UTC, nadiakhoptiuk requested changes

2023-06-19 09:33 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    gap: 104px;
тут gap 136px

2023-06-19 12:52 UTC, nadiakhoptiuk commented on src/views/Consultations/PersonalConsultationsView/PersonalConsultationsView.module.css
> +    gap: 104px;
все вірно за макетом 1280

2023-06-19 14:19 UTC, merged