Reusable Blue Component [Beta]
SoftRyzen-internship/psychologist pull request #12
Opened 2023-06-09 23:47 UTC by MagisterUnivers

2023-06-10 06:30 UTC, nadiakhoptiuk requested changes

2023-06-10 06:30 UTC, nadiakhoptiuk commented on public/icons/TabletMainVector.svg
ці файли фонові треба викачати png, бо там є фон голубий, якого не буде видно в цьому випадку

2023-06-10 06:30 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.jsx
> +        className={
className={blueBoxClassName} і далі при використанні передають клас із усіма стилями

2023-06-10 06:30 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.jsx
> +      <section
по семантиці це не буде секція, а буде певний дів з шириною 100%, він потім буде всередину секції вкладатись

2023-06-10 06:30 UTC, nadiakhoptiuk commented on src/content/consultations/blue.md
цей файл буде відноситись до сторінки головної

2023-06-10 09:41 UTC, MagisterUnivers commented on public/icons/TabletMainVector.svg
Теперь все стало понятно. А я то просто уже перепробовал все варианты стилизации, чтобы заблюрить его синим таким.

Спасибо, сделаю

2023-06-10 09:42 UTC, MagisterUnivers commented on src/content/consultations/blue.md
Перенесу, бета все таки.

2023-06-20 10:57 UTC, nadiakhoptiuk requested changes

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.jsx
> +};
додати типізацію пропсів

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.module.css
> +@media screen and (min-width: 768px) {
впорядкувати медіаправила (2 медіа: 768, 1280)

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/pages/consultations.js
> +      <BlueSectionComponent
підключати потрібно всередині в'юшки, яку потім підключимо на сторінку
цей бокс завжди відноситься до секції по своїй тематиці

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/pages/consultations.js
> +const ConsultationsPage = props => {
додати типізацію пропсів

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.module.css
> +/* .reusableSection p:not(:first-of-type) {
прибрати коментарі

2023-06-20 10:57 UTC, nadiakhoptiuk commented on src/components/BlueSection/BlueSection.module.css
> +/* .hello {
коментарі зайві

2023-06-20 12:52 UTC, nadiakhoptiuk approved these changes

2023-06-20 12:53 UTC, merged