WorkingMethodSection --> PersonalConsultation Page
SoftRyzen-internship/psychologist pull request #13
Opened 2023-06-10 00:58 UTC by MagisterUnivers

2023-06-13 14:08 UTC, nadiakhoptiuk requested changes

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +};
+

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +.image2 {
+

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +@media screen and (min-width: 768px) {
+

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +            alt="method2 img"
+

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +          <div className={s.textWrapper}>
Не согласен. Не будет разницы

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +            alt="method1 img"
+

2023-06-13 18:55 UTC, MagisterUnivers commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +import classNames from 'classnames';
+

2023-06-16 10:23 UTC, nadiakhoptiuk commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethod.jsx
> +            width={320}
1. на мобільному картинки тягнуться 100% всюди, давай і тут так зробиш
2. немає верхнього відступу у першої картинки на телефоні
3. відступ верхній у другої картинки створюється за рахунок того, що випадає нижній відступ від p, потрібно перенести його на дів text-Wrapper

2023-06-16 10:32 UTC, nadiakhoptiuk requested changes

2023-06-16 10:32 UTC, nadiakhoptiuk commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +@media screen and (min-width: 320px) and (max-width: 479.98px) {
ось чому картинки не розтягуються.. просто прибери тут медіаправило, нехай ці селектори будуть вгорі

2023-06-16 10:32 UTC, nadiakhoptiuk commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +    margin-bottom: 0;
width: 336px
так само на таблеті для textWrapper width: 336px додати
для image2 width: 336px також додати

2023-06-16 10:32 UTC, nadiakhoptiuk commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +    margin-bottom: 36px;
додати margin-bottom: 0 для останнього wrapper і останнього абзацу всередині - для таблета і десктопа

2023-06-19 10:02 UTC, nadiakhoptiuk commented on src/views/PersonalConsultationMethodView/PersonalConsultationMethodView.module.css
> +    margin-bottom: 36px;
для мобільного - для останнього абзацу всередині блоку тексту перенести нижні марджини на батьківські контейнери.
на таблеті перевірити, чи скидаються

2023-06-19 10:03 UTC, nadiakhoptiuk requested changes

2023-06-19 14:49 UTC, nadiakhoptiuk approved these changes

2023-06-19 14:49 UTC, merged