Reusable/socials
SoftRyzen-internship/psychologist pull request #19
Opened 2023-06-13 23:07 UTC by anatoliitrehub

2023-06-15 12:04 UTC, nadiakhoptiuk requested changes

2023-06-15 13:07 UTC, anatoliitrehub commented on src/components/FixedSocials/FixedSocials.jsx
>    useEffect(() => {
ok

2023-06-15 13:08 UTC, anatoliitrehub commented on src/components/FixedSocials/FixedSocials.jsx
>    useEffect(() => {
то у різний час було, тому виправив. Він приймає саме компонент, куди рендериться

2023-06-15 13:18 UTC, anatoliitrehub commented on src/components/FixedSocials/FixedSocials.module.css
>    right: 0;
ok

2023-06-15 13:22 UTC, anatoliitrehub commented on src/components/MobileMenu/MobileMenu.module.css
в модулі NavBar виправив

2023-06-15 13:26 UTC, anatoliitrehub commented on src/components/Socials/Socials.jsx
> +export const Socials = ({ component = 'panel' }) => {
додав

2023-06-15 13:29 UTC, anatoliitrehub commented on src/components/Socials/Socials.jsx
> +  const links = {
ok

2023-06-15 13:40 UTC, anatoliitrehub commented on src/components/Socials/Socials.jsx
> +          <a href={links.youtube} target="_blank" rel="noreferrer noopener">
rel додав, тут кнопок немає, тільки дінки, на бургер на кнопку додав aria-label

2023-06-15 14:09 UTC, anatoliitrehub commented on src/pages/index.js
> +        <FixedSocials />
ok

2023-06-15 14:13 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.jsx
> +            alt="main hero photo"
ok

2023-06-15 14:15 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.jsx
> +            height={745}
ok

2023-06-15 14:21 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +.imageBox {
ok

2023-06-15 15:24 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 742px;
не зрозумів де саме

2023-06-15 15:24 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +    padding-left: 62px;
розміри залишив, транслейт змінив на absolute

2023-06-15 15:36 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 742px;
в цього image класу

2023-06-15 15:50 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +  const links = {
бачу, виніс, файл має бути json, а не jsx
index.jsx - теж не те. або js, або взагалі прибери його

2023-06-15 15:55 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +          <a href={links.youtube} target="_blank" rel="noreferrer noopener">
на лінки теж треба. це іконки, які читалки не прочитають, потрібно додавати лейбли

2023-06-15 16:38 UTC, nadiakhoptiuk requested changes

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +
на first на мобільному додати верхній марджин

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +.intro {
на intro на мобілку додати width: 242px;
! перевірити всі font-weight, є 300, 400... не 700

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    padding-top: 52px;
pt: 69px

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    margin-left: 329px;
ml: auto;

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    padding-bottom: 15px;
зайвий

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 100%;
width прибрати,

додати pt: 62px
height: 755px

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 742px;
height: 692px !

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +  display: none;
прибрати, вже додав через стейт

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
>    width: 100vw;
width зайве

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 745px;
734 висота картинки

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    width: 100vw;
width: 100vw; прибрати

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    top: -30px;
top: 0, якщо pt на секції 62

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    line-height: 1.13;
додати h1 для десктопа, mb: 36px

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 100%;
height: 796px

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    margin-left: 485px;
можна ml замінити на mr: 41px або transform: translateX(-41px)

2023-06-15 16:38 UTC, nadiakhoptiuk commented on src/pages/index.js
> +import PropTypes from 'prop-types';
proptypes наверх

2023-06-15 17:10 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
>    width: 100vw;
ok

2023-06-15 17:10 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +  display: none;
неуважний, ок

2023-06-15 17:19 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +
так він же є у first та second, нижче

2023-06-15 17:51 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +    margin-left: 329px;
ok

2023-06-15 17:55 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 742px;
ok

2023-06-15 18:27 UTC, anatoliitrehub commented on src/views/Home/HomeHero/HomeHero.module.css
> +.intro {
по макету 238пс, тому поставив 238, на інших поставив 100% щоб перебити

2023-06-16 08:47 UTC, nadiakhoptiuk requested changes

2023-06-16 08:47 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +            href={links[0].telegram}
додати aria-label на всі лінки

2023-06-16 08:47 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +.intro {
вірно, 238. але воно в тебе не виглядає як на макеті, переноситься, бо треба перебити font-weight, за  макетом 600

.intro > p > strong { 
font-weight: 600;
}

2023-06-16 08:47 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    margin-top: 36px;
margin-top: 36 прибрати

2023-06-16 08:47 UTC, nadiakhoptiuk commented on src/views/Home/HomeHero/HomeHero.module.css
> +    height: 100%;
не додав.
якщо перенести рядки так як на макеті, то все поїде скоріш за все
тому додай висоту

2023-06-16 08:47 UTC, nadiakhoptiuk commented on src/content/home/hero.md
> +  Дійсний член Товариства символдрами України імені Ханскарла Лейнера. Експерт Інституту політичної освіти (ІПО, Київ).
тут повинно бути 4 рядки

2023-06-16 10:37 UTC, anatoliitrehub commented on src/components/Socials/Socials.jsx
> +            href={links[0].telegram}
ok

2023-06-16 16:34 UTC, nadiakhoptiuk approved these changes

2023-06-16 16:35 UTC, merged