Feature modal
SoftRyzen-internship/psychologist pull request #21
Opened 2023-06-14 10:06 UTC by Hanna-Bazdyrieva

2023-06-14 14:13 UTC, nadiakhoptiuk requested changes

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.module.css
>    counter-reset: my-awesome-counter;
додати стилі тексту

font-weight: 600;
font-size: 16px;
line-height: 24px;
/* or 150% */

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.module.css
додати стилі для списку ol

font-weight: 600;
font-size: 18px;
line-height: 28px;
/* or 156% */

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  priority
це секція, яка внизу малюється, тут priority не потрібно, це тільки для тих, які в області перегляду відразу

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  alt="contour drawing of wooman with a book"
альт повинен бути мовою сайту - українською

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  alt="contour drawing of wooman with a book"
альт повинен бути мовою сайту - українською

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  alt="contour drawing of of team watching to laptop"
альт повинен бути мовою сайту - українською

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  priority
це секція, яка внизу малюється, тут priority не потрібно, це тільки для тих, які в області перегляду відразу

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  priority
це секція, яка внизу малюється, тут priority не потрібно, це тільки для тих, які в області перегляду відразу

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>                  alt="contour drawing of of team watching to laptop"
альт повинен бути мовою сайту - українською

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/views/See-Far-CBT/EducationProgramView/EducationProgramView.jsx
>              </MediaQuery>
ще внизу потрібна типізація для пропса

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/components/ContactForm/ContactForm.module.css
> +  /* color: #ffffff;
зайві коментарі прибрати

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/components/ContactForm/ContactForm.module.css
> +  /* @media screen and (max-width: 374px) {
прибрати зайві коментарі

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/components/ContactForm/ContactForm.module.css
> +  /* @include tablet {
зайві коментарі прибрати

2023-06-14 14:13 UTC, nadiakhoptiuk commented on src/components/ContactForm/ContactForm.jsx
> +            {/* {touched.acceptedTerms && errors.acceptedTerms ? (
коментарі прибрати, якщо вже не потрібні

2023-06-14 15:43 UTC, Hanna-Bazdyrieva commented on package.json
> +    "@radix-ui/react-slot": "^1.0.2",
done

2023-06-14 15:46 UTC, Hanna-Bazdyrieva commented on public/icons/tick1.svg
done

2023-06-14 15:54 UTC, Hanna-Bazdyrieva commented on public/icons/tick.svg
done

2023-06-14 15:55 UTC, Hanna-Bazdyrieva commented on src/components/ActionButton/ActionButton.module.css
> +/* @media screen and (max-width: 767px) {
done

2023-06-14 15:58 UTC, Hanna-Bazdyrieva commented on src/components/ContactForm/ContactForm.jsx
> +import s from './ContactForm.module.css';
done

2023-06-14 16:19 UTC, Hanna-Bazdyrieva commented on src/components/ContactForm/ContactForm.module.css
> +  margin: 0 auto 20px;
в макеті 20 32 32, перевірила

2023-06-15 10:03 UTC, nadiakhoptiuk requested changes

2023-06-15 12:11 UTC, merged