create section consult
SoftRyzen-internship/psychologist pull request #30
Opened 2023-06-18 09:57 UTC by anatoliitrehub

секція зроблена з dev, з урахуванням зауважень що у закритій гілці

2023-06-19 10:34 UTC, nadiakhoptiuk requested changes

2023-06-19 10:34 UTC, nadiakhoptiuk commented on src/layout/Layout/Layout.jsx
> +      <FixedSocials />
перенеси сюди зі сторінки index.js main:

```
<main className="main">
       {children}

       <FixedSocials />
</main>
```

2023-06-19 10:34 UTC, nadiakhoptiuk commented on src/pages/index.js
> +        <Consult />
потрібно прибрати тег main в лейаут

2023-06-19 10:34 UTC, nadiakhoptiuk commented on src/views/Home/Consult/Consult.module.css
> +  height: 148px;
розміри - наверх

2023-06-19 10:34 UTC, nadiakhoptiuk commented on src/views/Home/Consult/Consult.module.css
> +.section {
зафіксуй ширину h2 203px для мобільної версії, і 736 для десктопа

2023-06-19 10:34 UTC, nadiakhoptiuk commented on src/views/Home/Consult/Consult.module.css
> +.item:nth-child(1) {
зафіксувати ширину першого span 
для моб 167px, таблет - 196px, десктоп- 216

2023-06-19 18:50 UTC, anatoliitrehub commented on src/layout/Layout/Layout.jsx
> +      <FixedSocials />
ok

2023-06-19 18:54 UTC, anatoliitrehub commented on src/pages/index.js
> +        <Consult />
ok

2023-06-19 18:55 UTC, anatoliitrehub commented on src/views/Home/Consult/Consult.module.css
> +  height: 148px;
ok

2023-06-19 19:35 UTC, anatoliitrehub commented on src/views/Home/Consult/Consult.module.css
> +.section {
для моб ок, для десктоп стрибає ліворуч, тому поставив падінги

2023-06-19 19:46 UTC, anatoliitrehub commented on src/views/Home/Consult/Consult.module.css
> +.item:nth-child(1) {
ok

2023-06-20 08:13 UTC, nadiakhoptiuk commented on src/layout/Layout/Layout.jsx
> +      <FixedSocials />
всередину main
https://prnt.sc/zEKyOhltKees

2023-06-20 08:13 UTC, nadiakhoptiuk commented on src/views/Home/Consult/Consult.module.css
> +.section {
```
width: 736px;
    margin-left: auto;
    margin-right: auto;
```

2023-06-20 08:14 UTC, nadiakhoptiuk requested changes
ще мінімальні правки

2023-06-20 09:06 UTC, anatoliitrehub commented on src/layout/Layout/Layout.jsx
> +      <FixedSocials />
ok

2023-06-20 09:08 UTC, anatoliitrehub commented on src/views/Home/Consult/Consult.module.css
> +.section {
ok

2023-06-20 10:13 UTC, nadiakhoptiuk approved these changes

2023-06-20 10:14 UTC, merged