correct bugs
SoftRyzen-internship/psychologist pull request #4
Opened 2023-06-07 21:46 UTC by anatoliitrehub

2023-06-08 20:28 UTC, nadiakhoptiuk requested changes

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +  const currentPath = usePathname();
import { useRouter } from 'next/router';  

const router = useRouter();
  const currentPath = router.pathname;

по документації в /pages usePathname недоступний

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.jsx
> +                onClick={() => mobileOpen(false)}
краще винести в якусь функцію
handleClick = ()=> {

if(!isDesktop) {
setIsMenuOpen(false)
}
}


і передати onClick={handleClick }
1. щоразу не реєструється колбек
2. іде перевірка, чи треба взагалі меню закривати

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.module.css
> +  list-style-type: none;
list-style-type: none; перенеси в самий низ

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/NavBar/NavBar.module.css
> +@media screen and (max-width: 1279px) {
медіаправило із вмістом перенести після всіх класів вниз

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +import { Logo } from '@/components/Logo/Logo';
Logo, NavBar, MobBurger, MobileMenu - зробити реекспорт через index.js
імпортувати стилі в самому низу імпортів

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +    <Container className={classStat}>
вміст меню потрібно ще огорнути в якийсь div з 100vh i 100 vw, бо з боків світиться

2023-06-08 20:28 UTC, nadiakhoptiuk commented on src/components/MobBurger/MobBurger.module.css
> +@media screen and (min-width: 1279px) {
це правило зайве, ми рендеримо бургер тільки до десктопа через js

2023-06-09 14:55 UTC, nadiakhoptiuk requested changes

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/components/MobBurger/MobBurger.jsx
> +      <button className={st.burger} onClick={() => setIsMenuOpen(!isMenuOpen)}>
() => setIsMenuOpen(!isMenuOpen)
краще винести у функцію handleClick наприклад, щоб не реєструвати щоразу колбек

onClick={handleClick}

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +import { Socials } from '../Socials/Socials';
NavBar, Socials -  змінити на реекспорт з index.js папки components

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +import Telegram from '../../../public/icons/soctelegram.svg';
попробуй писати вручну ось так:
import Telegram from 'public/icons/soctelegram.svg';

спеціально є в конфігу аліаси, щоб не було макаронів)

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +          <a href="#">
target, rel додати
краще винести у json шляхи і посилання, і мепнути

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/layout/Header/Header.jsx
> +import { Logo } from '@/components/Logo/Logo';
ще це потрібно
імпорти з папки components

2023-06-09 14:55 UTC, nadiakhoptiuk commented on src/layout/Header/Header.module.css
> +  position: relative;
перемістити наверх position

2023-06-10 14:33 UTC, nadiakhoptiuk requested changes

2023-06-10 14:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.jsx
> +    <div className={wrapStat}>
тут всі анімації транслейт і опасіті мають стояти на цьому діву (з контейнера треба прибрати)

тому ось така картина: менюшка завжди над сайтом [скрін](https://prnt.sc/-_Ery9JllYXA)

2023-06-10 14:33 UTC, nadiakhoptiuk commented on src/components/MobileMenu/MobileMenu.module.css
> +  height: calc(100vh - 71px);
тільки тут 72px

2023-06-10 14:33 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.module.css
> +  stroke: #2361ab;
для іконок видалити колір в самій svg fill='#23,,...'
на іконку (тут) написати

fill: currentColor;

і змінювати її колір через батьківський .list

2023-06-10 14:33 UTC, nadiakhoptiuk commented on src/components/Socials/Socials.jsx
> +      <ul className={st.list}>
тут додати пропом клас (щоб можна було передати колір)

2023-06-10 18:22 UTC, anatoliitrehub commented on src/components/MobileMenu/MobileMenu.module.css
> +  height: calc(100vh - 71px);
після зміни імпорту лого трохи розміри змінилися

2023-06-10 18:36 UTC, anatoliitrehub commented on src/components/Socials/Socials.jsx
> +      <ul className={st.list}>
компонент поки що недороблений щоб передавати різний колір

2023-06-12 11:37 UTC, nadiakhoptiuk approved these changes

2023-06-12 11:38 UTC, merged