Main requests
SoftRyzen-internship/psychologist pull request #40
Opened 2023-06-20 20:44 UTC by anatoliitrehub

в цій гілці 2 секції

2023-06-21 10:05 UTC, nadiakhoptiuk requested changes

2023-06-21 10:05 UTC, nadiakhoptiuk commented on src/views/Home/HomeTrainings/HomeTrainings.module.css
> +  width: 100%;
відступ вниз від зображення відсутній

2023-06-21 10:05 UTC, nadiakhoptiuk commented on src/views/Home/HomeTrainings/HomeTrainings.module.css
> +    width: 332px;
323

2023-06-21 12:24 UTC, anatoliitrehub commented on src/views/Home/HomeTrainings/HomeTrainings.jsx
> +  const Trainitems = {
ok

2023-06-21 12:58 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
> +              quality={100}
ok

2023-06-21 12:58 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
> +              quality={100}
ok

2023-06-21 12:58 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
> +              quality={100}
ok

2023-06-21 12:59 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
> +import { ReusableSection, OffsetImageBorder } from '@/components';
ok

2023-06-21 15:09 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.module.css
> +    aspect-ratio: 576 / 572;
ok

2023-06-21 15:54 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.module.css
> +.mdContent li {
ok

2023-06-21 16:08 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
це ж окрема секція Андрія, додам на сторінку

2023-06-22 08:04 UTC, nadiakhoptiuk requested changes

2023-06-22 11:21 UTC, anatoliitrehub commented on src/views/Home/HomeTrainings/HomeTrainings.jsx
> +                quality={100}
ok

2023-06-22 11:23 UTC, anatoliitrehub commented on src/views/Home/HomeTrainings/HomeTrainings.jsx
> +          <ReactMarkdown className={st.variant}>
ok

2023-06-22 11:27 UTC, anatoliitrehub commented on src/views/Home/HomeTrainings/HomeTrainings.module.css
> +  margin-bottom: 16px;
ok

2023-06-22 11:29 UTC, anatoliitrehub commented on src/views/Home/Requests/Requests.jsx
ok

2023-06-22 13:00 UTC, merged