SelectSection reusable component for main + personal consultations
SoftRyzen-internship/psychologist pull request #6
Opened 2023-06-08 07:27 UTC by MagisterUnivers

2023-06-09 10:22 UTC, nadiakhoptiuk requested changes

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/components/SectionSelect/SectionSelect.jsx
> +            <button type="button" className={s.buttonTest}>
заміни на ActionButton

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/components/SectionSelect/SectionSelect.jsx
> +// const SectionSelect = ({ whatido, study }) => {
закоментоване забери собі кудись у сторонню папку, якщо тобі потрібно

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/components/SectionSelect/SectionSelect.jsx
> +const SectionSelect = ({ data, src, alt, pos }) => {
pos заміни на position, не дуже ясно

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/components/SectionSelect/SectionSelect.jsx
> +        <h2
тут краще було використати SectionTitle компонент із пропом title={data.heading}

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/components/SectionSelect/SectionSelect.jsx
> +export default SectionSelect;
додай, будь ласка, типізацію

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/content/main/study.md
> +  - id: 1
рендерити список з одного елемента не має сенсу

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/content/main/whatido.md
> +  - id: 1
один елемент списку...

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/consultations.js
> +      {console.log(individual, online, requirements, factors)}
це прибрати

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/consultations.js
> +// import ReactMarkdown from 'react-markdown';
це теж прибери, тут не буде парсу

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/index.js
> +// import { FirstView } from '@/views';
це можна прибрати і взагалі компонент видалити

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/index.js
> +import SectionSelect from '@/components/SectionSelect/SectionSelect';
реекспорт через index.js

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/index.js
> +        {/* <FirstView /> */}
видалити також)

2023-06-09 10:22 UTC, nadiakhoptiuk commented on src/pages/index.js
> -  const { allNews } = await getNewsList();
ці рядки будуть потрібні на головній, дані з адмінки

2023-06-09 11:08 UTC, MagisterUnivers commented on src/components/SectionSelect/SectionSelect.jsx
> +            <button type="button" className={s.buttonTest}>
+

2023-06-09 11:08 UTC, MagisterUnivers commented on src/components/SectionSelect/SectionSelect.jsx
> +// const SectionSelect = ({ whatido, study }) => {
+

2023-06-09 11:08 UTC, MagisterUnivers commented on src/components/SectionSelect/SectionSelect.jsx
> +const SectionSelect = ({ data, src, alt, pos }) => {
+

2023-06-09 11:08 UTC, MagisterUnivers commented on src/components/SectionSelect/SectionSelect.jsx
> +        <h2
+

2023-06-09 11:14 UTC, MagisterUnivers commented on src/components/SectionSelect/SectionSelect.jsx
> +export default SectionSelect;
+

2023-06-09 11:14 UTC, MagisterUnivers commented on src/pages/consultations.js
> +// import ReactMarkdown from 'react-markdown';
+

2023-06-09 11:15 UTC, MagisterUnivers commented on src/pages/index.js
> +// import { FirstView } from '@/views';
+

2023-06-09 11:17 UTC, MagisterUnivers commented on src/pages/index.js
> +        {/* <FirstView /> */}
+

2023-06-09 11:19 UTC, MagisterUnivers commented on src/pages/index.js
> -  const { allNews } = await getNewsList();
+

2023-06-09 11:30 UTC, MagisterUnivers commented on src/pages/index.js
> +import SectionSelect from '@/components/SectionSelect/SectionSelect';
+

2023-06-14 08:14 UTC, nadiakhoptiuk commented
написала самостійно приклад компоненту та його використання. цей код не ввійде у дев

2023-06-14 08:14 UTC, closed without merging